[package]
name = "kaduox-ssh-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kssh-daemon"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
kaduox-ssh-core = { path = "../kaduox-ssh-core" }
kaduox-ssh-hosts = { path = "../kaduox-ssh-hosts" }
tokio.workspace = true
