[package]
name = "kaduox-ssh-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
russh.workspace = true
russh-config.workspace = true
russh-sftp.workspace = true
tokio.workspace = true
