[package]
name = "kaduox-ssh-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kssh"
path = "src/main.rs"

[[bin]]
name = "kssh-tui"
path = "src/tui_main.rs"

[[bin]]
name = "kssh-fleet"
path = "src/fleet_main.rs"

[[bin]]
name = "kssh-inventory"
path = "src/inventory_main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
kaduox-ssh-core = { path = "../kaduox-ssh-core" }
rpassword.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
