name: Security Audit

on:
  push:
  pull_request:
  schedule:
    - cron: '23 5 * * 1'

permissions:
  contents: read

jobs:
  rustsec:
    name: RustSec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
